substitutions:
  id_name: rnw_esphm_c3_01_workshop_heater
  friendly_name: esp32c3-workshop-heater

esphome:
  name: ${friendly_name}
  friendly_name: ${friendly_name}
  project:
    name: "zatakon.vevor-heater"
    version: "1.2.0"  # Library version with daily consumption fix

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG  # Use USB JTAG for logging on ESP32-C3

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "Workshop Heater Fallback"
    password: "fallback123"

captive_portal:

web_server:
  local: True
  port: 80

# Time component for daily consumption reset
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Prague  # Change to your timezone

# Add the library
external_components:
  - source:
      type: local
      path: components
    components: [vevor_heater]

# I2C configuration for sensors
i2c:
  scl: GPIO8
  sda: GPIO7
  scan: true
  id: bus_a

# UART configuration for Vevor heater
uart:
  - id: heater_serial
    rx_pin: 
      number: GPIO3
      inverted: true
    tx_pin:
      number: GPIO0
      inverted: true
    baud_rate: 4800

# Main heater component with automatic sensor creation
# Using MANUAL mode
vevor_heater:
  id: my_heater
  uart_id: heater_serial
  time_id: sntp_time
  external_temperature_sensor: workshop_temperature_sensor  # Required for antifreeze mode
  default_power_percent: 80      # Default 80% power when turned on
  injected_per_pulse: 0.022      # Initial value (in ml)
  polling_interval: 300s         # Poll status every 300 seconds when heater is OFF (default: 300s)
  min_voltage_start: 12.3        # Default, can be changed
  min_voltage_operate: 11.4      # Default, can be changed
  antifreeze_temp_on: 1.8        # Turn on at 80% below this
  antifreeze_temp_medium: 4.0    # Set 50% power above this
  antifreeze_temp_low: 5.0       # Set 20% power above this
  antifreeze_temp_off: 5.8       # Turn off above this temperature
  auto_mode_temp_below: -3.0     # Turn on when temp is 3°C below target (for automatic mode)
  auto_mode_temp_above: 2.0      # Turn off when temp is 2°C above target (for automatic mode)
  # Optional control components:
  reset_total_consumption_button:
    name: "Reset Total Fuel Consumption"
  control_mode_select:
    name: "Heater Control Mode"
  power_level_number:
    name: "Heater Power Level"
  target_temperature_number:
    name: "Target Temperature"

sensor:
  - platform: adc
    pin: GPIO1
    name: "Voltage"
    update_interval: 5s
    attenuation: auto
    filters:
      - multiply: 1.0  # Adjust multiplier based on your voltage divider if needed
  
  - platform: aht10
    i2c_id: bus_a
    temperature:
      id: workshop_temperature_sensor
      name: "Workshop temperature"
    humidity:
      id: workshop_humidity_sensor
      name: "Workshop humidity"
    update_interval: 10s
