substitutions:
  id_name: rnw_esphm_c3_01_workshop_heater
  friendly_name: esp32c3-workshop-heater

external_components:
  - source: github://zatakon/esphome-vevor-heater@v1.3.0
    components: [vevor_heater]

esphome:
  name: ${friendly_name}
  friendly_name: ${friendly_name}
  project:
    name: "zatakon.vevor-heater"
    version: "1.3.0"  

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG  # Use USB JTAG for logging on ESP32-C3

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "Workshop Heater Fallback"
    password: "fallback123"

captive_portal:

web_server:
  local: True
  port: 80

# UART configuration for Vevor heater
uart:
  - id: heater_serial
    rx_pin: 
      number: GPIO1
      inverted: true
    tx_pin:
      number: GPIO0
      inverted: true
    baud_rate: 4800

# Main heater component with automatic sensor creation
# Using MANUAL mode
vevor_heater:
  id: my_heater
  uart_id: heater_serial
  control_mode: manual           # Manual mode - heater runs at set power level
  default_power_percent: 80      # Default 80% power when turned on
  injected_per_pulse: 0.022      # Initial value (in ml)
  
  # Optional: Add integrated controls (v1.3.0+)
  control_mode_select:
    name: "Heater Control Mode"
  power_switch:
    name: "Heater Power"
  power_level_number:
    name: "Heater Power Level"
  reset_total_consumption_button:
    name: "Reset Total Fuel Consumption"
  
  # Optional: Configure antifreeze mode thresholds (v1.3.0+)
  # Requires external_temperature_sensor to be set
  # antifreeze_temp_on: 2.0        # Start heating below this temp (80% power)
  # antifreeze_temp_medium: 6.0    # Switch to 50% power above this
  # antifreeze_temp_low: 8.0       # Switch to 20% power above this
  # antifreeze_temp_off: 9.0       # Turn off above this temp

